### ISSUE TITLE
init.sh doesn't install python3

### ISSUE THREAD

**Issue by pegurnee** [pegurnee-group/cosc592_big_data#2]

**Comment by Josep313** [comment]
This is implied the init.sh will only run on cloudera, otherwise thats more checking

**Comment by pegurnee** [comment]
cloudera doesn't boot with python3

**Comment by pegurnee** [comment]
it also doesn't yum install python3

**Comment by Josep313** [comment]
I'm flying blind without cloudera on my laptop. I'll test it today

On Monday, April 4, 2016, Eddie Gurnee notifications@github.com wrote:

> it also doesn't yum install python3
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/pegurnee-group/cosc592_big_data/issues/2#issuecomment-205283448

## 
- Joseph Johnson
  E01259838
